### ISSUE TITLE
Error on downloading package

### ISSUE THREAD

**Issue by Marlysson** [mschwager/cohesion#1]
I ran the command:

```pip install cohesion```

and show me result :

```
Downloading/unpacking cohesion
  Could not find any downloads that satisfy the requirement cohesion
No distributions at all found for cohesion
Storing complete log in /home/cliente/.pip/pip.log
```

Seeing the pip.log file:

```bash
Downloading/unpacking cohesion

  Getting page http://pypi.python.org/simple/cohesion
  URLs to search for versions for cohesion:
  * http://pypi.python.org/simple/cohesion/
  Getting page http://pypi.python.org/simple/cohesion/
  Analyzing links from page https://pypi.python.org/simple/cohesion/
    Skipping link https://pypi.python.org/packages/9d/56/536846a677d672f6176eccbc66d4da05101960ef755e865d36df3a3fbc25/cohesion-0.5.0-py2.py3-none-any.whl#md5=f735e4fa689b77313edb46c6434e7df5 (from https://pypi.python.org/simple/cohesion/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/e1/db/2b29b55958681a994a52a06767465426cf1952ea9218a73f9c00926694c3/cohesion-0.5.1-py2.py3-none-any.whl#md5=0b5fc31e76753afb20c7e320318295a5 (from https://pypi.python.org/simple/cohesion/); unknown archive format: .whl
  Could not find any downloads that satisfy the requirement cohesion

No distributions at all found for cohesion

Exception information:
Traceback (most recent call last):
  File "/home/cliente/Dev/Apps/redes/tests/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/home/cliente/Dev/Apps/redes/tests/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/cliente/Dev/Apps/redes/tests/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 978, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/cliente/Dev/Apps/redes/tests/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/index.py", line 157, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for cohesion
```

**Comment by mschwager** [comment]
It looks like the problem you're having is because of the following statement:

```
unknown archive format: .whl
```

Which, I believe, is because `setuptools` is out-of-date. I would try running the following command, then install `cohesion` again:

```
$ pip install --upgrade setuptools
```

You can find more information here: http://stackoverflow.com/a/20950487
