### ISSUE TITLE
ValueError: 'float' is not callable

### ISSUE THREAD

**Issue by KyleKing** [mschwager/cohesion#17]
This might be from a change in Python 3.11 or flake 6, but I think this line should be: `'type': float,`:

https://github.com/mschwager/cohesion/blob/d0e77f1394b5fc82bb81a6a645d4eab0ffd89e8b/lib/cohesion/flake8_extension.py#L23

If not, I get the below error:

```sh
Traceback (most recent call last):
  File "./.venv/bin/flake8", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "./.venv/lib/python3.11/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "./.venv/lib/python3.11/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "./.venv/lib/python3.11/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "./.venv/lib/python3.11/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
                                 ^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.11/site-packages/flake8/options/parse_args.py", line 51, in parse_args
    option_manager.register_plugins(plugins)
  File "./.venv/lib/python3.11/site-packages/flake8/options/manager.py", line 259, in register_plugins
    add_options(self)
  File "./.venv/lib/python3.11/site-packages/cohesion/flake8_extension.py", line 36, in add_options
    parser.add_option(flag, **kwargs)
  File "./.venv/lib/python3.11/site-packages/flake8/options/manager.py", line 282, in add_option
    self._current_group.add_argument(*option_args, **option_kwargs)
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/argparse.py", line 1448, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: 'float' is not callable
```

When `self._current_group.add_argument(*option_args, **option_kwargs)` are:

```python
['--cohesion-below']
{'action': 'store', 'default': 50.0, 'type': 'float', 'help': 'only show cohesion results with this percentage or lower'}
```

Environment:

```sh
Python 3.11.2
flake8==6.0.0
cohesion==1.0.0
```

**Comment by mschwager** [comment]
Hey, thanks for the heads up!

Would you be interested in testing the fix and submitting a PR?

**Comment by mschwager** [comment]
Interestingly, `flake8` still uses the string `type` in their docs here: https://flake8.pycqa.org/en/latest/plugin-development/plugin-parameters.html#registering-options, e.g. `type='int'`. But I do see that this may have been deprecated as far back as `flake8` `3.8.0`: https://flake8.pycqa.org/en/latest/release-notes/3.8.0.html#id4.

Further, in their internal API docs (https://flake8.pycqa.org/en/5.0.4/internal/option_handling.html#api-documentation) it says this of `type`:

> type ([Union](https://docs.python.org/3/library/typing.html#typing.Union)[[str](https://docs.python.org/3/library/stdtypes.html#str), [Callable](https://docs.python.org/3/library/typing.html#typing.Callable)[[...], [Any](https://docs.python.org/3/library/typing.html#typing.Any)], _ARG]) – A callable to normalize the type (as is the case in [argparse](https://docs.python.org/3/library/argparse.html#module-argparse)). Deprecated: you can also pass through type strings such as 'int' which are handled by [optparse](https://docs.python.org/3/library/optparse.html#module-optparse).

So, as of `5.0.4` (the internal API docs are no longer available in 6), it was a union of `str` and `callable`. All this is to say, I believe you're correct that changing the code to `'type': float` should do the trick :+1:

**Comment by KyleKing** [comment]
Thanks for digging into the issue!

I'd be happy to submit a PR and test older versions of flake8. I'll submit something this week unless you want to knock it out sooner

**Comment by KyleKing** [comment]
Looks like the change is backward compatible. I did a quick check with `nox` and while I didn't have Python 2 installed, I checked a range of `flake8` versions back to 2019 and the only issues in the test appeared to be Python-version related and not cohesion

```sh
nox > Ran multiple sessions:
nox > * extract_cases-3.7(flake8_version='6.0.0'): failed
nox > * extract_cases-3.7(flake8_version='5.0.4'): success
nox > * extract_cases-3.7(flake8_version='4.0.1'): success
nox > * extract_cases-3.7(flake8_version='3.9.2'): failed
nox > * extract_cases-3.7(flake8_version='3.6.0'): success
nox > * extract_cases-3.11(flake8_version='6.0.0'): success
nox > * extract_cases-3.11(flake8_version='5.0.4'): success
nox > * extract_cases-3.11(flake8_version='4.0.1'): success
nox > * extract_cases-3.11(flake8_version='3.9.2'): success
nox > * extract_cases-3.11(flake8_version='3.6.0'): failed
```

Code:

```py
# noxfile.py
import nox


@nox.session(python=["3.7", "3.11"], reuse_venv=True)
# https://github.com/PyCQA/flake8/tags
@nox.parametrize("flake8_version", ["6.0.0", "5.0.4", "4.0.1", "3.9.2", "3.6.0"])
def extract_cases(session: nox.Session, flake8_version: str) -> None:
    session.run("pip", "install", f"flake8=={flake8_version}", stdout=True)
    session.run("python", "setup.py", "install", stdout=True)
    session.run("python", "-m", "flake8", "--help", stdout=True)
    session.run("python", "-m", "flake8", "setup.py", stdout=True)
    session.run("python", "-m", "flake8", "./lib/cohesion/module.py", "--cohesion-below=50", stdout=True)
```

To replicate, choose whichever major Python versions you have installed (`nox` should recognize `.tool-versions` or installation methods), install `nox` (`pipx install nox`), and run the content of the noxfile shown above (with `nox`)

> I'm stepping out for a bit, but I'll follow up with a PR and on the specific failures

**Comment by KyleKing** [comment]
Flake8 6.0.0 only supports Python >=3.8.1

Then, this is the error for Python 3.11 and Flake8 3.6.0, which is unrelated to the change:

```sh
nox > python -m flake8 ./lib/cohesion/module.py --cohesion-below=15 --exit-zero
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/checker.py", line 451, in run_check
    return plugin["plugin"](**arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/plugins/pyflakes.py", line 99, in __init__
    super(FlakesChecker, self).__init__(
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 498, in __init__
    self.runDeferred(self._deferredFunctions)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 535, in runDeferred
    handler()
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 1228, in runFunction
    self.handleNode(stmt, node)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 1146, in RETURN
    self.handleNode(node.value, node)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 870, in handleNode
    handler = self.getNodeHandler(node.__class__)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/pyflakes/checker.py", line 700, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
                                               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/checker.py", line 682, in _run_checks
    return checker.run_checks()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/checker.py", line 612, in run_checks
    self.run_ast_checks()
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/checker.py", line 513, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/checker.py", line 456, in run_check
    raise exceptions.PluginExecutionFailed(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/exceptions.py", line 86, in __init__
    self.original_exception = kwargs.pop("exception")
                              ^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'exception'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/__main__.py", line 4, in <module>
    cli.main()
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/main/application.py", line 412, in run
    self._run(argv)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/main/application.py", line 400, in _run
    self.run_checks()
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/main/application.py", line 318, in run_checks
    self.file_checker_manager.run()
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/checker.py", line 338, in run
    self.run_parallel()
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-11-flake8_version-3-6-0/lib/python3.11/site-packages/flake8/checker.py", line 302, in run_parallel
    for ret in pool_map:
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
KeyError: 'exception'
```

Then there was an error for Python 3.7 and Flake8 3.9.2:

```sh
nox > python -m flake8 setup.py
Traceback (most recent call last):
  File "/Users/kyleking/.asdf/installs/python/3.7.12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/kyleking/.asdf/installs/python/3.7.12/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-7-flake8_version-3-9-2/lib/python3.7/site-packages/flake8/__main__.py", line 4, in <module>
    cli.main()
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-7-flake8_version-3-9-2/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-7-flake8_version-3-9-2/lib/python3.7/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-7-flake8_version-3-9-2/lib/python3.7/site-packages/flake8/main/application.py", line 350, in _run
    self.initialize(argv)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-7-flake8_version-3-9-2/lib/python3.7/site-packages/flake8/main/application.py", line 330, in initialize
    self.find_plugins(config_finder)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-7-flake8_version-3-9-2/lib/python3.7/site-packages/flake8/main/application.py", line 153, in find_plugins
    self.check_plugins = plugin_manager.Checkers(local_plugins.extension)
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-7-flake8_version-3-9-2/lib/python3.7/site-packages/flake8/plugins/manager.py", line 357, in __init__
    self.namespace, local_plugins=local_plugins
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-7-flake8_version-3-9-2/lib/python3.7/site-packages/flake8/plugins/manager.py", line 238, in __init__
    self._load_entrypoint_plugins()
  File "/Users/kyleking/Developer/Pull-Requests/cohesion/.nox/extract_cases-3-7-flake8_version-3-9-2/lib/python3.7/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
    eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'
```

**Comment by KyleKing** [comment]
Then as a sanity check, I ran `rm -rf .nox` and replaced `session.run("python", "setup.py", "install")` with `session.run("pip", "install", "cohesion==1.0.0")`

This confirmed that this issue only exists on Flake8 6.0.0 and Python 3.11!

```sh
nox > Command python -m flake8 ./lib/cohesion/module.py --cohesion-below=15 --exit-zero failed with exit code 1
nox > Session extract_cases-3.11(flake8_version='3.6.0') failed.
nox > Ran multiple sessions:
nox > * extract_cases-3.7(flake8_version='6.0.0'): failed
nox > * extract_cases-3.7(flake8_version='5.0.4'): success
nox > * extract_cases-3.7(flake8_version='4.0.1'): success
nox > * extract_cases-3.7(flake8_version='3.9.2'): failed
nox > * extract_cases-3.7(flake8_version='3.6.0'): success
nox > * extract_cases-3.11(flake8_version='6.0.0'): failed
nox > * extract_cases-3.11(flake8_version='5.0.4'): success
nox > * extract_cases-3.11(flake8_version='4.0.1'): success
nox > * extract_cases-3.11(flake8_version='3.9.2'): success
nox > * extract_cases-3.11(flake8_version='3.6.0'): failed 
```
