### ISSUE TITLE
Unable to specify `cohesion-below` option via `setup.cfg`

### ISSUE THREAD

**Issue by sobolevn** [mschwager/cohesion#9]
Hi, thanks for this plugin. I am working on integrating it into our linter: https://github.com/wemake-services/wemake-python-styleguide/issues/134

But, currently there's an issue with configuration. 

```
_______________ FLAKE8-check(ignoring N802 D100 D104 D106 D401) ________________
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/flake8/checker.py", line 648, in _run_checks
    return checker.run_checks()
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/flake8/checker.py", line 579, in run_checks
    self.run_ast_checks()
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/flake8/checker.py", line 493, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/cohesion/flake8_extension.py", line 44, in run
    file_module.filter_below(self.cohesion_below)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/cohesion/module.py", line 79, in filter_below
    self._filter(predicate)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/cohesion/module.py", line 43, in _filter
    for class_name, class_structure in self.structure.items()
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/cohesion/module.py", line 44, in <dictcomp>
    if predicate(class_name)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/cohesion/module.py", line 77, in predicate
    return operator.le(class_percentage, percentage)
TypeError: '<=' not supported between instances of 'float' and 'str'
"""

The above exception was the direct cause of the following exception:
.venv/lib/python3.6/site-packages/pluggy/hooks.py:258: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
.venv/lib/python3.6/site-packages/pluggy/manager.py:67: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
.venv/lib/python3.6/site-packages/pluggy/manager.py:61: in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
.venv/lib/python3.6/site-packages/_pytest/runner.py:111: in pytest_runtest_call
    item.runtest()
.venv/lib/python3.6/site-packages/pytest_flake8.py:117: in runtest
    self.statistics)
.venv/lib/python3.6/site-packages/py/_io/capture.py:150: in call
    res = func(*args, **kwargs)
.venv/lib/python3.6/site-packages/pytest_flake8.py:193: in check_file
    app.run_checks([str(path)])
.venv/lib/python3.6/site-packages/flake8/main/application.py:310: in run_checks
    self.file_checker_manager.run()
.venv/lib/python3.6/site-packages/flake8/checker.py:319: in run
    self.run_parallel()
.venv/lib/python3.6/site-packages/flake8/checker.py:288: in run_parallel
    for ret in pool_map:
/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py:735: in next
    raise value
E   TypeError: '<=' not supported between instances of 'float' and 'str'
```

Here's how to reproduce it.

1. install `flake8` and `cohesion`
2. create `setup.cfg` with the following contents:

```ini
[flake8]
cohesion-below = 100.0
```

3. Run `flake8` on any file with a `class` inside, for example the one from the readme.

Here's related `flake8` information:

```
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "39.0.1"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.5",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "cohesion",
      "version": "0.8.0"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.3.1"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "1.6.0"
    }
  ],
  "version": "3.5.0"
}
```

**Comment by mschwager** [comment]
Huh, interesting!

I'm guessing it's interpreting `100.0` actually as `"100.0"`, and thus can't compare a string with a float in `predicate`. I'll investigate further, try to reproduce, and get back to you!

**Comment by mschwager** [comment]
Nice catch, as it turns out this is a bug upstream in `flake8`: https://gitlab.com/pycqa/flake8/issues/452

I'll update my code to force turning the option data received into a `float`, though, so we don't have to wait for a new version of `flake8`.

(And so my code works with old versions of `flake8` assuming it gets patched)

**Comment by sobolevn** [comment]
@mschwager nice, thanks!

**Comment by mschwager** [comment]
Hah! The saga continues...

As I was confirming my fix I was suddenly having trouble reproducing. Turns out `float` and `str` comparisons have different behavior on Python 2 vs. Python 3:

Python 2:
```
In [8]: 10.0 < '100.0'
Out[8]: True

In [9]: 10.0 < '0.0'
Out[9]: True

In [10]: 10.0 < ''
Out[10]: True
```

Python 3:
```
In [1]: 10.0 < '100.0'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-8becb88a113b> in <module>()
----> 1 10.0 < '100.0'

TypeError: unorderable types: float() < str()

In [2]: 10.0 < '0.0'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-423d001eda71> in <module>()
----> 1 10.0 < '0.0'

TypeError: unorderable types: float() < str()

In [3]: 10.0 < ''
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-f062f1a4ad3a> in <module>()
----> 1 10.0 < ''

TypeError: unorderable types: float() < str()
```

Wat... what the heck is Python 2 doing... Anyways I was running under Python 2 and expecting an exception, but never getting one. But the fix is coming soon.

**Comment by mschwager** [comment]
I just released a new version: https://pypi.org/project/cohesion/0.9.0/

Let me know if that fixes your issue :+1:
